import { Article } from './datainterface';

//Blog article below
/*
*id: +1 from previous
*themePic: '/assets/img/id-theme.jpg
*article: any pictures should be <img src='/assets/img/1-picA.png'> '/assets/img/id'-pic'A-Za-z'.jpg. Placement of picture should use class='right|center|left'
*/
export const ARTICLE: Article[] = [
    {
        "id": 0,
        "themePic": "/assets/img/0-theme.png",
        "attrPic": "Photo by RetroSupply on Unsplash",
        "themeText": "Angular blog on Github pages",
        "author": "Brian Venter",
        "date": "2021-05-13T08:29:08.273Z",
        "summary": "Creating a blog by using an Angular Single Page Application and a text file database",
        "article": [
            { "type": "p", "content": "This blog is built with Angular and served by Github pages. The database for this blog is a text file. That last sentence is correct, it is not a typo."},
            { "type": "p", "content": "One of the challenges with hosting a progressive blog by means of Github pages is storing the articles. And there are a number of challenges with this. If you host the database somewhere else, any connection authentication details will be open for all to see. One can serve static pages for each new article, but this doesn't quite fit the idea of using a framework. So how does this blog work? Well, you may already be examining the code (open an issue if you have some positive criticism to share), but here is the general breakdown."},
            { "type": "p", "content": "The framework, as mentioned, is Angular along with the Material library. This simplifies much of the development of the Single Page Application and its general theming. The database is a text file. To be precise, it is a TypeScript text file. Each article is an array item and themed according to the key-value pair. The string contents of the <i>article</i> key has HTML tags included for basic layout (paragraphs, bold, italics, img, etc) The blog is deployed to Github pages using the npm package angular-cli-ghpages."},
            { "type": "p", "content": "<i>Is this the most efficient way to have a blog?</i> No. <i>Can it easily scale?</i> No. <b>So why do it this way?</b> Let us put aside the not-so-witty 'because I can'. For one, it is a neat exercise in getting to know Angular, SPAs and Github pages. It also provides a simple setup that helps illustrate the various components, templates, modules and routing that make up an Angular application. And the text file database is a reasonable starting point for understanding Observables and working with a data service. By no means is this blog a best practice or easy rollout revolutionary. For me, though, it is an interesting learning path. And that really is the purpose of this blog: capturing lessons learned in the telecommunications industry whilst at the same time learning new concepts and dabbling in different programming languages."},
            { "type": "p", "content": "I am not a prolific writer, and thus this blog will not be growing at a rapid rate. However, some day it really may not be a practical SPA if I am still using the text file as my database. At that point I will likely implement an API gateway (like Labstack's Echo server written in Go) and database server, while tweaking the Angular SPA's code to GET the article information using its HTTPClient utility. But I may keep the latest three articles as part of the text database - just in case someone can benefit from it."},
            { "type": "p", "content": "If you have any suggestions - CSS, HTML, Angular, or something else related - feel free to open an issue. There is always room for improvement."},
        ]
    },
    {
        "id": 1,
        "themePic": "/assets/img/1-theme.png",
        "attrPic": "Photo by Brian Venter",
        "themeText": "MXONE in Azure Cloud",
        "author": "Brian Venter",
        "date": "2021-04-29T08:53:44.970Z",
        "summary": "Setting up Mitel's MXONE on Azure with Linux CLI - Part 1",
        "article": [
            { "type": "p", "content": "I have been keen on testing Mitel's MXONE in the cloud ever since the Azure image was released. This also required becoming more acquainted with Microsoft's Azure platform. And I want to do this without booting into Windows. It would need to be a purely Linux experience on my end."},
            { "type": "p", "content": "In this first part I document practical first steps with Azure and getting your Linux environment prepared. In the parts to follow we will create the Resource Group and network for the MXONE. We will also set up a point-to-site VPN. From there will get a small virtual machine up and SSH to it. This virtual machine is a temporary one and its purpose is purely to get the MXONE's VHD extracted and copie across. (The extracted VHD is 100GB in size and the copy always failed after a long wait. Instead, I copied the 7GB compressed file up to a temporary virtual machine, unzip it and copy it across as a managed disk)."},
            { "type": "h2", "content": "Getting started"},
            { "type": "p", "content": "I won't go through setting up an Azure account. But there is one suggestion I have: setup balance warnings and limits in Azure. This is crucial to avoid having costs run away from you."},
            { "type": "p", "content": "Let's get the Azure client software installed (<a href='https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=zypper'>link</a>). Here are the commands for openSuse:"},
            { "type": "code-bash", "content": "sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc\nsudo zypper addrepo --name 'Azure CLI' --check https://packages.microsoft.com/yumrepos/azure-cli azure-cli\nsudo zypper install --from azure-cli azure-cli"},
            { "type": "p", "content": "Although this walkthrough uses AZCopy on the temporary virtual machine, I am going to document it at this point for reference. <a href='https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-and-install-azcopy'>Download</a> and extract it. For ease of use, you can do the following to make it executable from anywhere if you are using BaSH:"},
            { "type": "p", "content": "Make the binary executable: "},
            { "type": "code-bash", "content": "chmod +x /path/to/azcopy"},
            { "type": "p", "content": "Edit <b>.bashrc</b> and add the following to the end of the file:"},
            { "type": "code-bash", "content": "alias azcopy=/path/to/azcopy"},
            { "type": "p", "content": "Save and exit file. Exit your shell and/or start a new one.\nTest your Azure CLI and AZCopy installations:"},
            { "type": "code-bash", "content": "az login "},
            { "type": "span", "content": "will login your Azure CLI."},
            { "type": "code-bash", "content": "azcopy login --tenant-id 'tenant-id-as-see-in-az-login-output'"},
            { "type": "span", "content": "will login your azcopy client."},
            {"type": "br", "content": ""},
            { "type": "p", "content": "AZCopy was still a bit buggy with logins. Even on brand new virtual machines. Whether I used Ubuntu or openSuse. Fortunately the errors are pretty well documented with solutions - although at first you will think the problem is on your side. Some issues are experienced with keyctl, others occur because the Python install isn't from homebrew. If you find your AZCopy login fails at this point: search the error along with azcopy. There is a good chance the problem and solution has already been documented."},
            { "type": "p", "content": "So at this point you have your Azure setup and are ready to run some API commands. In the <a href='./blog/2'>next part</a> we will setup the Azure Resource Group for the MX-ONE."},
        ]
    },
    {
        "id": 2,
        "themePic": "/assets/img/2-theme.png",
        "attrPic": "Photo by Brian Venter",
        "themeText": "MXONE Network in Azure",
        "author": "Brian Venter",
        "date": "2021-06-11T15:29:31.781Z",
        "summary": "Setting up Mitel's MXONE on Azure with Linux CLI - Part 2",
        "article":[
            {"type": "p", "content": "<a href='./blog/1'>Last time</a> we got Azure ready for use. In this part we will create the Resource Group, which really creates the Azure environment for our MXONE. In a production environment, the Resource Group may be an existing one. (Read more about the Resource Group <a href='https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal#what-is-a-resource-group'> here</a>) As part of the resource group, we will:"},
            {"type": "li", "content": "Specify the data center region to locate our voice network"},
            {"type": "li", "content": "Create the network and subnet for our call, media and database server(s)"},
            {"type": "li", "content": "Create a P2S (Point-2-site) VPN"},
            {"type": "span", "content": "<i>In production, the VPN would be S2S (site-to-site), but for this exercise we will just register a softphone from our machine to the MXONE we have in Azure.</i>"},
            {"type": "br", "content": ""},
            {"type": "br", "content": ""},
            {"type": "h2", "content": "Make life easier"},
            {"type": "p", "content": "...by gathering your data ahead of time into environment variables. Here is a table of some of the environment variables you will use quite often."},
            {"type": "table-border-1", "content": "", "table": [ ["ENV", "What we used", "Notes"], ["MXRESGRP", "MxoneTest", "A descriptive name of your choice"], ["MXREGION", "southafricanorth", "Data center region. Use the command <i>az account list-locations -o table</i> to get a list, or visit <a href='https://azure.microsoft.com/en-au/global-infrastructure/geographies/'>here</a>"], ["MXVNET", "mxnet", "Main virtual network name for this RG"], ["MXSUBNET", "mxSubnetA", "Name for the subnet being used for the MXONE / voice services"], ["MXVPN", "MXvpnIP", "Descriptive name for VPN."], ["MXVPNGW", "MXVPNGateway", "Name of the VPN Gateway"] ]},
            {"type": "br", "content": ""},
            {"type": "br", "content": ""},
            {"type": "p", "content": "Here is an example network setup that we will be initiating:"},
            {"type": "img", "content": "/assets/img/2-picC.png"},
            {"type": "h2", "content": "Get going"},
            {"type": "p", "content": "Assuming that you have logged in (<i>az login</i>) with Azure CLI client, we can create our resource group:"},
            {"type": "code-bash", "content": "az group create --name $MXRESGRP -l $MXREGION"},
            {"type": "p", "content": "Next, let's create the network:"},
            {"type": "code-bash", "content": "az network vnet create --name $MXVNET --resource-group $MXRESGRP --location $MXREGION --address-prefix \"10.2.0.0/16\" --subnet-name $MXSUBNET --subnet-prefix \"10.2.3.0/24\""},
            {"type": "p", "content": "We also want to reserve two IP addresses: the MXONE base IP and the alias for Cassandra. We do this by creating NICs:"},
            {"type": "code-bash", "content": "az network nic create --name lim001Nic1 --resource-group $MXRESGRP --location $MXREGION --subnet $MXSUBNET --private-ip-address 10.2.3.4 --vnet-name $MXVNET --public-ip-address \"\""},
            {"type": "code-bash", "content": "az network nic create --name lim001Nic2 --resource-group $MXRESGRP --location $MXREGION --subnet $MXSUBNET --private-ip-address 10.2.3.5 --vnet-name $MXVNET --public-ip-address \"\""},
            {"type": "br", "content": ""},
            {"type": "h2", "content": "Getting a secure connection"},
            {"type": "p", "content": "<a href='https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-point-to-site-resource-manager-portal#creategw'>Here</a> is the reference material for setting up the VPN connection. Note that you do <b>not</b> want to use VPN gateway type \"Basic\". We start by getting a public IP: "},
            {"type": "code-bash", "content": "az network public-ip create -g $MXRESGRP -n $MXVPN"},
            {"type": "p", "content": "Next, we assign a portion of our Virtual Network to be used for VPN gateways. The name \"GatewaySubnet\" is required as is - it is not a custom label field:"},
            {"type": "code-bash", "content": "az network vnet subnet create --vnet-name $MXVNET -n \"GatewaySubnet\" -g $MXRESGRP --address-prefix \"10.2.1.0/27\""},
            {"type": "p", "content": "And now we can create the VPN gateway, linking it to the public IP we created and assigning a totally separate pool of addresses that can be assigned to VPN clients:"},
            {"type": "code-bash", "content": "az network vnet-gateway create -g $MXRESGRP -n $MXVPNGW --location $MXREGION --vnet $MXVNET --gateway-type Vpn --sku VpnGw2 --vpn-type RouteBased --address-prefixes \"10.9.9.0/27\" --vpn-gateway-generation Generation2 --public-ip-address $MXVPN --client-protocol IkeV2 OpenVPN"},
            {"type": "p", "content": "To view it:"},
            {"type": "code-bash", "content": "az network vnet-gateway list -g $MXRESGRP"},
            {"type": "br", "content": ""},
            {"type": "br", "content": ""},
            {"type": "p", "content": "To complete the VPN gateway setup, we need to load the Root CA. For our test environment, we can create one. Ensure that you have <b>ipsec</b> and <b>StrongSwan</b> installed."},
            {"type": "p", "content": "Create a directory where you want to create the certificates:"},
            {"type": "code-bash", "content": "mkdir -p azure-certs"},
            {"type": "code-bash", "content": "cd azure-certs"},
            {"type": "br", "content": ""},
            {"type": "p", "content": "Now we want to generate the Root certificate:"},
            {"type": "code-bash", "content": "sudo ipsec pki --gen --outform pem > caKey.pem"},
            {"type": "p", "content": "And put it in PEM format:"},
            {"type": "code-bash", "content": "sudo ipsec pki --self --in caKey.pem --dn \"CN=VPN CA\" --ca --outform pem > caCert.pem"},
            {"type": "br", "content": ""},
            {"type": "p", "content": "To import the certificate to our VPN Gateway, use "},
            {"type": "code-bash", "content": "openssl x509 -in /path/to/caCert.pem -outform der | base64 -w0 ; echo"},
            {"type": "p", "content": "to get it in the correct format for Azure (yes, you need to change /path/to/). I set it as an environment variable ($MXROOTCERT) for uploading as can be seen next:"},
            {"type": "code-bash", "content": "az network vnet-gateway root-cert create -g $MXRESGRP -n \"P2SRoot\" --gateway-name MXVPNGW --public-cert-data $MXROOTCERT"},
            {"type": "br", "content": ""},
            {"type": "br", "content": ""},
            {"type": "p", "content": "It is now time to get our client prepared. Start by generating a password and pass it to PASSWORD:"},
            {"type": "code-bash", "content": "apg -m 15 -n 1"},
            {"type": "p", "content": "Choose your username (I set USERNAME as \"test\").\nWith that chosen, generate the client certificate:"},
            {"type": "code-bash", "content": "sudo ipsec pki --gen --outform pem > \"${USERNAME}Key.pem\""},
            {"type": "code-bash", "content": "sudo ipsec pki --pub --in \"${USERNAME}Key.pem\" | sudo ipsec pki --issue --cacert caCert.pem --cakey caKey.pem --dn \"CN=${USERNAME}\" --san \"${USERNAME}\" --flag clientAuth --outform pem > \"${USERNAME}Cert.pem\""},
            {"type": "code-bash", "content": "openssl pkcs12 -in \"${USERNAME}Cert.pem\" -inkey \"${USERNAME}Key.pem\" -certfile caCert.pem -export -out \"${USERNAME}.p12\" -password \"pass:${PASSWORD}\""},
            {"type": "br", "content": ""},
            {"type": "p", "content": "Generate the VPN server config package prepared by Azure with"},
            {"type": "code-bash", "content": "az network vnet-gateway vpn-client generate -g $MXRESGRP -n $MXVPNGW"},
            {"type": "br", "content": ""},
            {"type": "p", "content": "Use the link from the output to download the archive. You can regenerate the download link if you missed it:"},
            {"type": "code-bash", "content": "az network vnet-gateway vpn-client show-url -g $MXRESGRP -n $MXVPNGW"},
            {"type": "br", "content": ""},
            {"type": "p", "content": "From the extracted archive, copy the \"Generic\\\\VPNServerRoot.cer\" to <b>/etc/ipsec.d/cacerts/</b>. Copy the <b>test.p12</b> from your generated certificates to <b>/etc/ipsec.d/private/</b>."},
            {"type": "p", "content": "Edit <b>/etc/ipsec.conf</b> to resemble the following picture. This information can be found in the XML file present in the VPN package archive you downloaded from Azure."},
            {"type": "br", "content": ""},
            {"type": "img", "content": "/assets/img/2-picA.png"},
            {"type": "br", "content": ""},
            {"type": "p", "content": "Next, edit <b>/etc/ipsec.secrets</b> to contain USERNAME and PASSWORD for the client certificate, as illustrated by the next image. Note too that the certificate type of P12 is specified."},
            {"type": "br", "content": ""},
            {"type": "img", "content": "/assets/img/2-picB.png"},
            {"type": "br", "content": ""},
            {"type": "p", "content": "You can get connected now by first restarting <b>ipsec</b> so that the new config is loaded, and then connecting:"},
            {"type": "code-bash", "content": "sudo ipsec restart"},
            {"type": "code-bash", "content": "sudo ipsec up azure"},
            {"type": "br", "content": ""},
            {"type": "p", "content": "You will note that the \"azure\" matches the entry in <b>/etc/ipsec.conf</b> (for those not that familiar with ipsec). You can disconnect by running: "},
            {"type": "code-bash", "content": "sudo ipsec down azure"},
            {"type": "br", "content": ""},
            {"type": "p", "content": "That completes Part 2: our Resource Group is created, as is our Networking - complete with VPN access. In the last part (<a href='./blog/3'>Part 3</a>) we will copy across the MXONE Azure image and use it to get an MXONE up and running."},
        ]
    },
    {
        "id": 3,
        "themePic": "/assets/img/2-theme.png",
        "attrPic": "Photo by Brian Venter",
        "themeText": "MXONE Deploy in Azure",
        "author": "Brian Venter",
        "date": "2025-05-09T12:45:30.781Z",
        "summary": "Setting up Mitel's MXONE on Azure with Linux CLI - Part 3",
        "article":[
            {"type": "p", "content": "Still in progress"},
        ]
    },
    {
        "id": 4,
        "themePic": "/assets/img/3-theme.png",
        "attrPic": "Photo by Brian Venter",
        "themeText": "MXONE: No accessible backup",
        "author": "Brian Venter",
        "date": "2025-05-10T15:23:30.781Z",
        "summary": "Solving alarm 0:56 'The system does not have an accessible backup'",
        "article":[
            {"type": "p", "content": "This article certainly covers a strange fault, since there  were no backup errors (<b>data_info</b>) I could detect. However, it also provided an insight into the workings of the MXONE - which is always valuable. My troubleshooting at the beginning can easily be faulted - and if you would have discovered the cause faster or easier, I congratulate you. But for everyone else who is mortal as I am, I am sure there will be some insights gained by sharing this account. As I said, this was a strange fault. Just to be sure, I performed a <b>data_backup</b>, and it was successful...or so it appeared. It might be more accurate to say the command completed successfully, but still the alarm persisted. Where to next?"},
            {"type": "img", "content": "/assets/img/3-theme.png"},
            {"type": "p", "content": "I jumped into Mitel’s knowledgebase (KMS) and came across an article close enough – SO5602, “MX-ONE: Cannot read from system database”. One of the symptoms was related to “No backup configuration found in database”. Reading the article was like a caffeine jolt (which, being around midnight was clearly needed) as I was quickly reminded of two further troubleshooting avenues:"},
            {"type": "li", "content": "<b><i>/var/log/messages</i></b> ...of course!"},
            {"type": "li", "content": "<b>nodetool status</b> … because, hey, if you get funny issues with the MXONE, check out Cassandra...&#128512; "},
            {"type": "p", "content": "I opted to first peruse <b><i>/var/log/messages</i></b>. Using <b>less</b> you can search by simply pressing the /-key and entering a search phrase. Searching is case sensitive. Search forward (n) or backward (N). And this is what I found…(apologies for the small image)"},
            {"type": "imgX", "content": "/assets/img/3-picA.png"},
            {"type": "p", "content": "<i>Inconsistent reload data, manual action needed</i>. So where is the variance? I decided to list the xdata files (<b><i>/var/opt/eri_sn/xdata/</i></b>) of each service node (LIM). And there, eventually, was some traction. LIM3 was not showing the same xdata structure as LIM1 & 4. In fact, when running <b>data_info</b> on LIM3, the printout differed from that on LIM1 & 4. And no matter how many “successful” <b>data_backup</b> I did, the actual results on LIM3 itself did not change. On LIM1 & 4 the structure kept updating to reflect only the latest three backups as expected."},
            {"type": "p", "content": "As a refesher from training, the MXONE currently has two restore areas. Data from the Cassandra database is pushed into csv files, and local service node data is stored in .D files. This is all combined into an xdata folder each time a <b>data_backup</b> is performed. And each service node's xdata is thus unique and required when restoring or restarting the services."},
            {"type": "p", "content": "So when running the command <b>data_info</b>, is it just a listing of the directory structure of <b><i>/var/opt/eri_sn/xdata/</i></b>? No. Rather, the backup information is saved in the Cassandra database – as the help topic for <b>data_backup</b> shows."},
            {"type": "img", "content": "/assets/img/3-picB.png"},
            {"type": "p", "content": "So what started as a backup issue is gradually developing into a database issue. Running <b>nodetool status</b> on the various Cassandra servers soon showed a pattern: the Cassandra node co-located with LIM3 saw itself as UN (Up and Normal) and the other nodes as DN (Down but Normal), while the other nodes saw each other as UN, and the LIM3 co-located node as DN. Now it made sense why the printout from <b>data_info</b> was inconsistent. A simple test could prove that a database node was very likely the cause of <b>data_backup</b> having inconsistent data across the service nodes."},
            {"type": "p", "content": "I stopped the database node on LIM3 (<b>systemctl stop mxone_db.service</b>). Then ran <b>data_info</b> again from LIM3 – and now the printout harmonised with the rest of the system, because LIM3 was forced to read from the other database nodes. Performing <b>data_backup</b> also resulted in the correct files being created on all the service nodes, and old ones being deleted. And yes, the original alarm cleared."},
            {"type": "p", "content": "By the way, here is a simple way to verify and compare across several service nodes (for those not already aware of the features in a POSIX shell):"},
            {"type": "code-bash", "content": "data_info && ssh limX@ip “data_info” && ssh limY@ip “data_info” && (...repeat for more service nodes)"},
            {"type": "code-bash", "content": "ls -al /var/opt/eri_sn/xdata/ && ssh limX@ip “ls -al /var/opt/eri_sn/xdata/” && ssh limY@ip “ls -al /var/opt/eri_sn/xdata/” && (...repeat for more service nodes)"},
            {"type": "p", "content": "You can do the same with <b>nodetool status</b> on the various Cassandra servers (remember that this command is only found where the database service is installed)."},
            {"type": "p", "content": "What was at fault with the  database node? When it comes to Cassandra on the MXONE, the error is usually one of the following (in order of likelihood):<br>1. NTP (QA1883) <br>2. Disk space (SO3941) <br>3. Java software version (RE3238)"},
            {"type": "p", "content": "In this case, NTP was the troublemaker."},
            {"type": "img", "content": "/assets/img/3-picC.png"},
        ]
    },
  ];
